using System.Collections;
using System.Collections.Generic;
using System.Linq;
using UnityEngine;

public class Part3_Ambulance2 : MonoBehaviour
{
    [Header("References")]
    public GameObject startNode;

    [Header("Part3 - Multiple Goals")]
    [Tooltip("List of delivery/collection locations (up to 10).")]
    public List<GameObject> goalNodes = new List<GameObject>();
    public int maxGoals = 10;

    [Header("Movement")]
    public float baseSpeed = 8f;
    [Range(0, 10)]
    public int numberOfItems = 3;
    public float waypointThreshold = 0.5f;
    public float turnSpeed = 5f;
    public float stopDurationAtGoal = 3f;

    [Header("Ant Colony Optimisation Parameters")]
    public int antCount = 20;
    public int maxIterations = 50;
    [Range(0.0f, 5.0f)]
    public float alpha = 1.0f;
    [Range(0.0f, 10.0f)]
    public float beta = 5.0f;
    [Range(0.0f, 1.0f)]
    public float evaporationRate = 0.5f;
    public float Q = 100f;

    [Header("Global Speeds")]
    public float maxReturnSpeed = 12f;

    [Header("Status for UI")]
    public float currentSpeed;
    public int itemsCarried;
    public float totalDistance;
    public string deliveryStatus;

    [Header("Collision Avoidance (Minimal)")]
    public float safeDistance = 3f;
    public float slowDownFactor = 0.35f;
    public float sideMoveSpeed = 2f;

    [Header("Patients")]
    public List<Transform> patientSlots = new List<Transform>();
    public List<GameObject> patientsToDeliver = new List<GameObject>();

    private List<Part3_Ambulance2> nearbyAgents = new List<Part3_Ambulance2>();

    private float currentMovementSpeed;
    private float targetSpeed;
    private float nominalMovementSpeed;

    private AStarManager aStarManager = new AStarManager();
    private List<Connection> currentPathConnections;

    // ACO helpers
    private List<GameObject> nodesForACO = new List<GameObject>(); // start + goal nodes
    private float[,] distanceMatrix;
    private float[,] pheromoneMatrix;

    private int encounterCount = 0;
    private float runStartTime;
    private float runDistance;

    void Start()
    {
        deliveryStatus = "In Progress";
        totalDistance = 0f;

        CalculateMovementSpeed();
        BuildGraphFromVisWaypoints();
        StartCoroutine(RunAmbulanceRoutine());
    }

    private void CalculateMovementSpeed()
    {
        float reductionFactor = 1.0f - (numberOfItems * 0.1f);
        reductionFactor = Mathf.Clamp(reductionFactor, 0.1f, 1.0f);

        nominalMovementSpeed = baseSpeed * reductionFactor;
        currentMovementSpeed = nominalMovementSpeed;
        targetSpeed = nominalMovementSpeed;
    }

    void BuildGraphFromVisWaypoints()
    {
        GameObject[] objs = GameObject.FindGameObjectsWithTag("Waypoint");

        foreach (GameObject wp in objs)
        {
            VisGraphWaypointManager mgr = wp.GetComponent<VisGraphWaypointManager>();
            if (mgr == null) continue;

            foreach (VisGraphConnection vconn in mgr.Connections)
            {
                if (vconn.ToNode != null)
                {
                    Connection conn = new Connection
                    {
                        FromNode = wp,
                        ToNode = vconn.ToNode
                    };
                    aStarManager.AddConnection(conn);
                }
            }
        }
    }

    IEnumerator RunAmbulanceRoutine()
    {
        AttachAllPatients();

        BuildNodesForACO();
        BuildDistanceMatrix();

        List<int> tour = RunACO();
        
        // Validate tour - check if all paths are reachable
        if (tour == null || tour.Count < 2)
        {
            Debug.LogError("[Part3_Ambulance2] Invalid tour generated by ACO!");
            deliveryStatus = "ERROR: Invalid Tour";
            yield break;
        }
        
        // Verify all paths in tour are valid
        for (int t = 0; t < tour.Count - 1; t++)
        {
            int fromIdx = tour[t];
            int toIdx = tour[t + 1];
            if (distanceMatrix[fromIdx, toIdx] == Mathf.Infinity)
            {
                Debug.LogErrorFormat("[Part3_Ambulance2] Tour contains unreachable path: {0} -> {1}. Cannot execute tour!", 
                    nodesForACO[fromIdx].name, nodesForACO[toIdx].name);
                deliveryStatus = "ERROR: Unreachable Path in Tour";
                yield break;
            }
        }

        transform.position = startNode.transform.position;
        runStartTime = Time.time;
        runDistance = 0f;

        for (int t = 0; t < tour.Count - 1; t++)
        {
            GameObject from = nodesForACO[tour[t]];
            GameObject to = nodesForACO[tour[t + 1]];

            List<Connection> conns = aStarManager.PathfindAStar(from, to);
            
            // Check if pathfinding failed (empty path)
            if (conns == null || conns.Count == 0)
            {
                Debug.LogErrorFormat("[Part3_Ambulance2] PATHFINDING FAILED: No path found from {0} to {1}. Agent will be stuck!", 
                    from != null ? from.name : "NULL", 
                    to != null ? to.name : "NULL");
                deliveryStatus = "ERROR: No Path Found";
                yield break; // Stop the routine
            }
            
            List<GameObject> pathNodes = ConnectionsToNodeList(conns, from);
            
            Debug.LogFormat("[Part3_Ambulance2] Moving from {0} to {1}, path has {2} connections", 
                from.name, to.name, conns.Count);

            yield return StartCoroutine(FollowNodes(pathNodes));

            // Deliver patient if at a goal node (not start) AND there are patients left
            if (to != startNode && HasPatientsToDeliver())
            {
                DropOnePatientAtCurrentPosition();

                // Stop and set speed to 0 while waiting
                currentSpeed = 0f;
                yield return new WaitForSeconds(stopDurationAtGoal);
            }


            // After all patients are delivered and agent returns to start,
            // the speed is already at its maximum from the last 10% boost,
            // so we don't change it here.
        }

        currentSpeed = 0f;
        deliveryStatus = "Delivered";

        float totalRunTime = Time.time - runStartTime;
        Debug.LogFormat("[Part3_Ambulance2] Tour completed. Total distance: {0:F2}, runtime: {1:F2}s, encounters: {2}", totalDistance, totalRunTime, encounterCount);
    }

    private bool HasPatientsToDeliver()
    {
        foreach (GameObject p in patientsToDeliver)
            if (p != null)
                return true;
        return false;
    }

    private void DropOnePatientAtCurrentPosition()
    {
        for (int i = 0; i < patientsToDeliver.Count; i++)
        {
            GameObject p = patientsToDeliver[i];
            if (p == null) continue;

            // Drop the patient
            patientsToDeliver[i] = null;
            p.transform.SetParent(null);
            p.transform.position = transform.position;
            p.transform.rotation = Quaternion.identity;

            Rigidbody rb = p.GetComponent<Rigidbody>();
            if (rb != null)
            {
                rb.isKinematic = false;
                rb.useGravity = true;
            }

            break; // drop one patient at a time
        }

        // Update itemsCarried
        itemsCarried = 0;
        foreach (Transform slot in patientSlots)
            if (slot.childCount > 0)
                itemsCarried++;

        // Increase speed by 10% after EVERY delivery (including the last one)
        // So an agent with N patients will get N successive 10% boosts
        nominalMovementSpeed *= 1.10f;
        targetSpeed = nominalMovementSpeed;
        currentMovementSpeed = nominalMovementSpeed;
    }

    private void ResetAllAgentsSpeed()
    {
        Part3_Ambulance2[] allAgents = FindObjectsOfType<Part3_Ambulance2>();
        foreach (var agent in allAgents)
        {
            agent.nominalMovementSpeed = agent.baseSpeed;
            agent.currentMovementSpeed = agent.baseSpeed;
            agent.targetSpeed = agent.baseSpeed;
        }
    }

    private void BuildNodesForACO()
    {
        nodesForACO.Clear();
        nodesForACO.Add(startNode);

        int count = Mathf.Min(goalNodes.Count, maxGoals);
        for (int i = 0; i < count; i++)
            if (goalNodes[i] != null)
                nodesForACO.Add(goalNodes[i]);
    }

    private void BuildDistanceMatrix()
    {
        int n = nodesForACO.Count;
        distanceMatrix = new float[n, n];
        pheromoneMatrix = new float[n, n];

        for (int i = 0; i < n; i++)
        {
            for (int j = 0; j < n; j++)
            {
                if (i == j) { distanceMatrix[i, j] = Mathf.Infinity; continue; }

                List<Connection> conns = aStarManager.PathfindAStar(nodesForACO[i], nodesForACO[j]);
                
                // If no path found, set distance to Infinity
                if (conns == null || conns.Count == 0)
                {
                    distanceMatrix[i, j] = Mathf.Infinity;
                    pheromoneMatrix[i, j] = 0f; // No pheromone for unreachable paths
                    Debug.LogWarningFormat("[Part3_Ambulance2] No path from {0} to {1} - setting distance to Infinity", 
                        nodesForACO[i].name, nodesForACO[j].name);
                    continue;
                }
                
                float dist = 0f;
                foreach (Connection c in conns)
                    dist += Vector3.Distance(c.FromNode.transform.position, c.ToNode.transform.position);

                distanceMatrix[i, j] = dist;
                pheromoneMatrix[i, j] = 1f;
            }
        }
    }

    private List<int> RunACO()
    {
        int n = nodesForACO.Count;
        List<int> bestTour = null;
        float bestLength = float.MaxValue;
        System.Random rng = new System.Random();

        for (int iter = 0; iter < maxIterations; iter++)
        {
            for (int ant = 0; ant < antCount; ant++)
            {
                List<int> tour = new List<int> { 0 };
                HashSet<int> visited = new HashSet<int> { 0 };

                while (visited.Count < n)
                {
                    int current = tour.Last();
                    int next = SelectNextNode(current, visited, rng);
                    tour.Add(next);
                    visited.Add(next);
                }

                tour.Add(0); // return to start

                float length = TourLength(tour);
                if (length < bestLength)
                {
                    bestLength = length;
                    bestTour = new List<int>(tour);
                }
            }

            EvaporatePheromones();
            DepositPheromones(bestTour, bestLength);
        }

        return bestTour;
    }

    private int SelectNextNode(int current, HashSet<int> visited, System.Random rng)
    {
        double sum = 0.0;
        Dictionary<int, double> probabilities = new Dictionary<int, double>();

        for (int j = 0; j < nodesForACO.Count; j++)
        {
            if (visited.Contains(j)) continue;
            // Skip unreachable nodes (Infinity distance)
            if (distanceMatrix[current, j] == Mathf.Infinity) continue;
            
            double val = System.Math.Pow(pheromoneMatrix[current, j], alpha) *
                         System.Math.Pow(1.0 / distanceMatrix[current, j], beta);
            probabilities[j] = val;
            sum += val;
        }
        
        // If no valid nodes found (all unreachable), return error
        if (probabilities.Count == 0)
        {
            Debug.LogErrorFormat("[Part3_Ambulance2] No reachable nodes from {0}!", nodesForACO[current].name);
            // Try to return to start if possible, otherwise return first unvisited node
            if (distanceMatrix[current, 0] != Mathf.Infinity && !visited.Contains(0))
                return 0;
            // Find any unvisited node that's reachable (shouldn't happen if graph is connected)
            for (int j = 0; j < nodesForACO.Count; j++)
                if (!visited.Contains(j) && distanceMatrix[current, j] != Mathf.Infinity)
                    return j;
            return 0; // Last resort
        }

        double pick = rng.NextDouble() * sum;
        double accum = 0.0;

        foreach (var kv in probabilities)
        {
            accum += kv.Value;
            if (pick <= accum)
                return kv.Key;
        }

        return probabilities.Keys.First();
    }

    private float TourLength(List<int> tour)
    {
        float length = 0f;
        for (int i = 0; i < tour.Count - 1; i++)
            length += distanceMatrix[tour[i], tour[i + 1]];
        return length;
    }

    private void EvaporatePheromones()
    {
        int n = nodesForACO.Count;
        for (int i = 0; i < n; i++)
            for (int j = 0; j < n; j++)
                pheromoneMatrix[i, j] *= (1f - evaporationRate);
    }

    private void DepositPheromones(List<int> tour, float length)
    {
        if (tour == null) return;
        float deposit = Q / Mathf.Max(length, 1e-6f);
        for (int i = 0; i < tour.Count - 1; i++)
        {
            int u = tour[i];
            int v = tour[i + 1];
            pheromoneMatrix[u, v] += deposit;
            pheromoneMatrix[v, u] += deposit;
        }
    }

    // --- Patient & Movement Logic ---
    private void AttachAllPatients()
    {
        deliveryStatus = "In Progress";

        int count = Mathf.Min(patientsToDeliver.Count, patientSlots.Count);

        for (int i = 0; i < count; i++)
        {
            GameObject p = patientsToDeliver[i];
            Transform slot = patientSlots[i];

            if (p == null || slot == null) continue;

            p.transform.SetParent(slot);
            p.transform.localPosition = Vector3.zero;
            p.transform.localRotation = Quaternion.identity;

            Rigidbody rb = p.GetComponent<Rigidbody>();
            if (rb != null)
            {
                rb.isKinematic = true;
                rb.useGravity = false;
            }
        }
    }

    private List<GameObject> ConnectionsToNodeList(List<Connection> conns, GameObject start)
    {
        List<GameObject> nodes = new List<GameObject> { start };
        foreach (Connection c in conns)
            nodes.Add(c.ToNode);
        return nodes;
    }

    private IEnumerator FollowNodes(List<GameObject> nodes)
    {
        foreach (GameObject node in nodes)
        {
            Vector3 targetPos = node.transform.position;

            while (Vector3.Distance(transform.position, targetPos) > waypointThreshold)
            {
                HandleCollisionAvoidance();

                currentMovementSpeed = Mathf.Lerp(currentMovementSpeed, targetSpeed, Time.deltaTime * 3f);
                Vector3 prevPos = transform.position;
                transform.position = Vector3.MoveTowards(transform.position, targetPos, currentMovementSpeed * Time.deltaTime);

                float moved = Vector3.Distance(transform.position, prevPos);
                totalDistance += moved;
                runDistance += moved;
                currentSpeed = moved > 0.001f ? currentMovementSpeed : 0f;

                itemsCarried = 0;
                foreach (Transform slot in patientSlots)
                    if (slot.childCount > 0) itemsCarried++;

                Vector3 direction = (targetPos - transform.position).normalized;
                if (direction != Vector3.zero)
                    transform.rotation = Quaternion.Slerp(transform.rotation, Quaternion.LookRotation(direction), turnSpeed * Time.deltaTime);

                yield return null;
            }
        }
    }

    private void HandleCollisionAvoidance()
    {
        nearbyAgents.RemoveAll(a => a == null);

        bool tooClose = false;
        Vector3 pushDir = Vector3.zero;

        foreach (Part3_Ambulance2 other in nearbyAgents)
        {
            float dist = Vector3.Distance(transform.position, other.transform.position);
            if (dist < safeDistance)
            {
                tooClose = true;
                pushDir += (transform.position - other.transform.position).normalized;
            }
        }

        if (tooClose)
        {
            targetSpeed = nominalMovementSpeed * slowDownFactor;
            transform.position += pushDir.normalized * sideMoveSpeed * Time.deltaTime;
        }
        else
        {
            targetSpeed = nominalMovementSpeed;
        }
    }

    void OnTriggerEnter(Collider other)
    {
        Part3_Ambulance2 agent = other.GetComponent<Part3_Ambulance2>();
        if (agent != null && agent != this && !nearbyAgents.Contains(agent))
        {
            nearbyAgents.Add(agent);
            encounterCount++;
        }
    }

    void OnTriggerExit(Collider other)
    {
        Part3_Ambulance2 agent = other.GetComponent<Part3_Ambulance2>();
        if (agent != null)
            nearbyAgents.Remove(agent);
    } 
}

